apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
spec:
  selector:
    app: mongodb  # Matches the label of the MongoDB Pods
  ports:
    - protocol: TCP
      port: 27017  # The port that the service will expose
      targetPort: 27017  # The port to forward traffic to in the container
  clusterIP: None  # Headless service to directly connect to Pods
